root: true

env:
    es6: true
    node: true
    jest: true

parser: 'babel-eslint'

globals:
    $: true

extends:
    - airbnb-base

parserOptions:
    sourceType: module

rules:
    indent:
        - error
        - 4
    linebreak-style: 'off'
    quotes:
        - error
        - single
    semi:
        - error
        - always
    camelcase: 0
    strict: 0
    max-len: [1, { code: 120 }]
    global-require: 0
    func-names: 0
    no-console: 0
    no-continue: 0
    no-plusplus: 0
    no-var: 2
    use-isnan: 2
    arrow-parens: 0
    comma-dangle: ['error', 'only-multiline']
    no-param-reassign: 0
    space-before-function-paren: 0
    object-curly-newline: 0
    array-callback-return: 0
    prefer-promise-reject-errors: 0
    no-await-in-loop: 0
    no-loop-func: 0
    no-buffer-constructor: 0
    no-underscore-dangle: 0
    no-use-before-define: 0
    no-prototype-builtins: 0
    no-lonely-if: 0
    no-restricted-syntax: 0
    prefer-destructuring: 0
    import/no-unresolved: [0, { commonjs: true, amd: true }]
    import/no-extraneous-dependencies: 0
    import/no-absolute-path: 0
    import/prefer-default-export: 0
    import/no-dynamic-require: 1
    import/extensions: ['off', 'always', { 'js': 'never' }]
    radix: 0
    guard-for-in: 0
    eol-last: 0
    object-curly-spacing: 0
